### ISSUE TITLE
Where is the data?

### ISSUE THREAD

**Issue by Benny0323** [Galaxies99/GANcon-pytorch#1]

**Comment by Benny0323** [comment]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/104205136/215688887-170ff9d1-5d0d-4ca1-a564-81425e8acc2e.png">

**Comment by Galaxies99** [comment]
Sorry for the late reply. 

I have not checked this repository for a long time since this is a **_personal_** re-implementation (therefore I am NOT the original author of the paper) of the GANcon paper on a third-party dataset, and this repository was one of the course projects during my undergraduate. 

The dataset I used was provided by the course instructor, so I have no permission to distribute the dataset.

If you are asking for the original data used in the original paper, I would suggest asking the original authors for help.
